- id: doi:10.1101/2023.12.20.572612
  image: https://www.biorxiv.org/content/biorxiv/early/2023/12/21/2023.12.20.572612/F10.large.jpg
- id: doi:10.1093/bioinformatics/btad419
  image: ../images/pubs/fortuna.jpeg
- id: doi:10.1093/nar/gkac403
  image: ../images/pubs/nar22_ccr4.jpeg
- id: doi:10.1002/cti2.1372
  image: ../images/pubs/cti22_crispr_tcell.jpg
- id: doi:10.1186/s13059-021-02356-5
  image: ../images/pubs/jsne.png
- id: doi:10.1093/bioinformatics/btaa1076
  image: ../images/pubs/biclustering.jpeg
- id: doi:10.1038/s41592-024-02168-y
  image: ../images/pubs/homotrimers.png
- id: doi:10.1016/j.ipl.2023.106454
  image: ../images/pubs/antichain_partitioning.png
- id: doi:10.1109/kse59128.2023.10299517
  image: ../images/pubs/jsne_ml.png
- id: doi:10.23919/mipro57284.2023.10159716
  image: ../images/pubs/fortuna_fly.jpg
- id: doi:10.1016/j.biopsych.2021.04.023
  image: ../images/pubs/cyfip1.png
