- id: doi:10.1101/2023.12.20.572612
  image: https://www.biorxiv.org/content/biorxiv/early/2023/12/21/2023.12.20.572612/F10.large.jpg
- id: doi:10.1093/bioinformatics/btad419
  image: ../images/pubs/fortuna.jpeg
- id: doi:10.1093/nar/gkac403
  image: ../images/pubs/nar22_ccr4.jpeg
- id: doi:10.1002/cti2.1372
  image: ../images/pubs/cti22_crispr_tcell.jpg
- id: doi:10.1186/s13059-021-02356-5
  image: ../images/pubs/jsne.png
- id: doi:10.1093/bioinformatics/btaa1076
  image: ../images/pubs/biclustering.jpeg
- id: doi:10.1038/s41592-024-02168-y
  image: ../images/pubs/homotrimers.png
- id: doi:10.1016/j.ipl.2023.106454
  image: ../images/pubs/antichain_partitioning.png
- id: doi:10.1109/kse59128.2023.10299517
  image: ../images/pubs/jsne_ml.png
- id: doi:10.23919/mipro57284.2023.10159716
  image: ../images/pubs/fortuna_fly.jpg
- id: doi:10.1016/j.biopsych.2021.04.023
  image: ../images/pubs/cyfip1.png
- id: doi:10.1038/s41590-022-01268-1
  image: ../images/pubs/wtap.png
- id: doi:10.23919/mipro55190.2022.9803685
  image: ../images/pubs/branchpoints.jpg
- id: doi:10.1038/s41587-021-01136-7
  image: ../images/pubs/ladder_logo_final.jpg

- id: doi:10.1101/2021.08.08.455218
  #title: Ccr4-Not complex reduces transcription efficiency in heterochromatin
- id: doi:10.1093/bioinformatics/btab050
  #title: 'McSplicer: a probabilistic model for estimating splice site usage from RNA-seq data'
- id: doi:10.1101/2021.06.24.449725
  #title: Metric Multidimensional Scaling for Large Single-Cell Data Sets using Neural Networks
- id: doi:10.1101/gr.267906.120
  #title: Linear-time cluster ensembles of large-scale single-cell RNA-seq and multimodal data
- id: doi:10.1101/2021.01.10.426098
  #title: A generalization of t-SNE and UMAP to single-cell multimodal omics
- id: doi:10.1038/s41375-020-0793-1
  #title: Leukemia-induced dysfunctional TIM-3+CD4+ bone marrow T cells increase risk of relapse in pediatric B-precursor ALL patients
- id: doi:10.1101/2020.08.10.243097
  #title: 'McSplicer: a probabilistic model for estimating splice site usage from RNA-seq data'
- id: doi:10.1261/rna.076026.120
  #title: Validation strategies for antibodies targeting modified ribonucleotides
- id: doi:10.1101/2020.06.15.151910
  #title: Linear-time cluster ensembles of large-scale single-cell RNA-seq and multimodal data
- id: doi:10.1016/j.isci.2020.101126
  #title: 'Sphetcher: Spherical Thresholding Improves Sketching of Single-Cell Transcriptomic Heterogeneity'
- id: doi:10.1038/s41375-020-0839-4
  #title: Clinical presentation and differential splicing of SRSF2, U2AF1 and SF3B1 mutations in patients with acute myeloid leukemia
- id: doi:10.1089/cmb.2019.0457
  #title: 'Chromatyping: Reconstructing Nucleosome Profiles from NOMe Sequencing Data'
- id: doi:10.1101/2020.01.31.926345
  #title: 'BiCoN: Network-constrained biclustering of patients and omics data'
- id: doi:10.1007/978-1-4939-9873-9
  #title: Protein-Protein Interaction Networks
- id: doi:10.1038/s41467-019-11076-1
  #title: Alternative splicing regulates stochastic NLRP3 activity
- id: doi:10.1093/bib/bby047
  #title: Exploring the functional impact of alternative splicing on human protein isoforms using available annotation sources
- id: doi:10.23919/mipro.2019.8756638
  #title: Properties of the generalized Robinson-Foulds metric
- id: doi:10.1016/j.cell.2019.02.010
  #title: A Common Embryonic Origin of Stem Cells Drives Developmental and Adult Neurogenesis
- id: doi:10.1074/mcp.ra118.001141
  #title: Proteome Analysis of Human Neutrophil Granulocytes From Patients With Monogenic Disease Using Data-independent Acquisition
- id: doi:10.1101/522672
  #title: Dynamic pseudo-time warping of complex single-cell trajectories
- id: doi:10.1007/978-1-4939-8808-2_15
  #title: Guided Reconstruction of Full-Length Isoforms from Short Reads by CIDANE
- id: doi:10.1038/s41467-018-07642-8
  #title: Genome wide association analysis in a mouse advanced intercross line
- id: doi:10.1016/j.disopt.2017.09.002
  #title: On the approximability of the maximum interval constrained coloring problem
- id: doi:10.1007/978-3-319-89929-9_2
  #title: 'Chromatyping: Reconstructing Nucleosome Profiles from NOMe Sequencing Data'
- id: doi:10.1007/978-1-4939-7710-9_5
  #title: Tracking Alternatively Spliced Isoforms from Long Reads by SpliceHunter
- id: doi:10.1016/j.cell.2017.09.003
  #title: Temporal Control of Mammalian Cortical Neurogenesis by m6A Methylation
- id: doi:10.1109/jproc.2015.2455551
  #title: 'Short Read Mapping: An Algorithmic Tour'
- id: doi:10.1101/gr.208041.116
  #title: The dynamic landscape of fission yeast meiosis alternative-splice isoforms
- id: doi:10.1093/bioinformatics/btw631
  #title: 'BASIC: BCR assembly from single cells'
- id: doi:10.1093/bioinformatics/btw447
  #title: "ModuleAlign: module-based global alignment of protein\u2013protein interaction networks"
- id: doi:10.1002/9781119272182.ch11
  #title: "Computational Methods for Transcript Assembly from RNA\u2010SEQ Reads"
- id: doi:10.1089/cmb.2015.0164
  #title: Resolving Conflicting Predictions from Multimapping Reads
- id: doi:10.1186/s13059-015-0865-0
  #title: 'CIDANE: comprehensive isoform discovery and abundance estimation'
- id: doi:10.1089/cmb.2013.0057
  #title: 'The Duplication-Loss Small Phylogeny Problem: From Cherries to Trees'
- id: doi:10.1145/2444016.2493372
  #title: A polynomial-delay algorithm for enumerating approximate solutions to the interval constrained coloring problem
- id: doi:10.1093/bioinformatics/btt273
  #title: 'GAGE-B: an evaluation of genome assemblers for bacterial organisms'
- id: doi:10.1007/s00453-013-9785-0
  #title: On Tree-Constrained Matchings and Generalizations
- id: doi:10.1089/cmb.2012.0239
  #title: Charge Group Partitioning in Biomolecular Simulation
- id: doi:10.1007/978-3-642-40453-5_13
  #title: The Generalized Robinson-Foulds Metric
- id: doi:10.1093/bioinformatics/bts566
  #title: 'CLEVER: clique-enumerating variant finder'
- id: doi:10.1137/1.9781611972924.8
  #title: Solving the Minimum String Cover Problem
- id: doi:10.1007/978-3-642-29627-7_3
  #title: Charge Group Partitioning in Biomolecular Simulation
- id: doi:10.1007/s11590-011-0308-0
  #title: An exact algorithm for side-chain placement in protein design
- id: doi:10.1007/978-3-642-23038-7_3
  #title: A Mathematical Programming Approach to Marker-Assisted Gene Pyramiding
- id: doi:10.1007/978-3-642-22006-7_9
  #title: On Tree-Constrained Matchings and Generalizations
- id: doi:10.1186/1471-2105-11-424
  #title: Computing H/D-Exchange rates of single residues from data of proteolytic fragments
- id: doi:10.1007/s00453-010-9406-0
  #title: Approximation Algorithms for the Interval Constrained Coloring Problem
- id: doi:10.1137/1.9781611972900.3
  #title: A Polynomial Delay Algorithm for Enumerating Approximate Solutions to the Interval Constrained Coloring Problem
- id: doi:10.1007/978-3-642-17514-5_15
  #title: On the Approximability of the Maximum Interval Constrained Coloring Problem
- id: doi:10.1145/1363686.1363981
  #title: Computing H/D-exchange speeds of single residues from data of peptic fragments
- id: doi:10.1007/s10878-008-9139-z
  #title: A Lagrangian relaxation approach for the multiple sequence alignment problem
- id: doi:10.1007/978-3-540-73556-4_29
  #title: A Lagrangian Relaxation Approach for the Multiple Sequence Alignment Problem
- id: doi:10.1007/978-3-540-69903-3_20
  #title: Approximating the Interval Constrained Coloring Problem
- id: doi:10.1101/017939
  #title: 'CIDANE: Comprehensive isoform discovery and abundance estimation'
- id: doi:10.1007/978-3-540-70600-7_38
  #title: 'LASA: A Tool for Non-heuristic Alignment of Multiple Sequences'
- id: doi:10.1101/045922
  #title: The dynamic landscape of fission yeast meiosis alternative-splice isoforms
