- id: doi:10.1101/2023.12.20.572612
  image: https://www.biorxiv.org/content/biorxiv/early/2023/12/21/2023.12.20.572612/F10.large.jpg
- id: doi:10.1093/bioinformatics/btad419
  image: ../images/pubs/fortuna.jpeg
- id: doi:10.1093/nar/gkac403
  image: ../images/pubs/nar22_ccr4.jpeg
- id: doi:10.1002/cti2.1372
  image: ../images/pubs/cti22_crispr_tcell.jpg
- id: doi:10.1186/s13059-021-02356-5
  image: ../images/pubs/jsne.png
